interface IPhoneConstants {
    phoneResellers: Array<string>;
    phoneBrands:  Array<string>;
    phoneColors: Array<string>;
}

export const phoneConstants: IPhoneConstants = {
    'phoneResellers': [
        'Aeris Communications Inc',
        'Affinity Cellular',
        'AirVoice Wireless',
        'AF Mobile',
        'Best Cellular',
        'Black Wireless',
        'Boom Mobile',
        'Boost Mobile',
        'Caffee Communications',
        'campusSIMs',
        'CellNUVO',
        'Cellular Abroad',
        'Charge',
        'Chit Chat Mobile',
        'Consumer Cellular',
        'Credo Mobile',
        'Cricket Wireless',
        'China Telecom Americas',
        'EasyGO Wireless',
        'EcoMobile',
        'enVie Mobile',
        'Espańol Mobile',
        'Expo Mobile',
        'FamilyTalk Wireless',
        'Flash Wireless',
        'FMP Wireless',
        'FreedomPop',
        'good2GO Mobile',
        'GoSmart Mobile',
        'GreatCall',
        'Hayai Mobile',
        'H2O Wireless',
        'KDDI Mobile',
        'Helio',
        'Infinium Wireless',
        'Jaguar Mobile',
        'Jolt Mobile',
        'Kajeet',
        'KidsConnect',
        'Kroger i-wireless',
        'Liberty Wireless',
        'LycaMobile',
        'Madstar Mobile',
        'MetroPCS',
        'Mint SIM',
        'Mobal',
        'Net10 Wireless',
        'NetZero',
        'NTT DoCoMo USA',
        'OTG Mobile',
        'Page Plus Cellular',
        'Patriot Mobile',
        'Pix Wireless',
        'Project Fi',
        'Proven Wireless',
        'Pure TalkUSA',
        'Puppy Wireless',
        'Ready Mobile',
        'Red Pocket Mobile',
        'Republic Wireless',
        'Roam Mobility',
        'ROK Mobile',
        'Scratch Wireless',
        'SeaWolf Wireless',
        'Selectel Wireless',
        'Simple Mobile',
        'SkyView Wireless',
        'Speed Talk Mobile',
        'Straight Talk',
        'Stream Wireless',
        'Telcel América',
        'Tello US',
        'Tempo Telecom',
        'TextNow',
        'The People\'s Operator USA',
        'Ting',
        'Total Call Mobile',
        'Total Wireless',
        'Touch Mobile',
        'TracFone',
        'Twigby',
        'Ultra Mobile',
        'US Mobile',
        'UVA Mobile',
        'UWT Mobile',
        'Value Wireless',
        'Virgin Mobile USA',
        'Walmart Family Mobile',
        'Wing',
        'Wireless Services US',
        'Xfinity Mobile',
        'Available to Comcast subscribers only',
        'Roams on wireless hotspots',
        'ZingPCS',
        'ZIP SIM',
        'Access Wireless',
        'Assurance Wireless',
        'Blue Jay Wireless',
        'Budget Mobile',
        'Entouch Wireless',
        'Feel Safe Wireless',
        'Life Wireless',
        'SafeLink Wireless',
        'SafetyNet Wireless',
        'TAG Mobile',
        'TruConnect',
        'Cbeyond',
        'Cognia Mobile',
        'Dataxoom',
        'Global Data Telecom',
        'Harbor Mobile',
        'MetTel Mobile',
        'Mobal Freedom',
        'Teltik',
        '7-Eleven Speak Out Wireless',
        'Amp\'d Mobile',
        'Aio Wireless',
        'Brightspot',
        'BYO Wireless',
        'BZRMobile',
        'Circle-K Talk-and-Go',
        'Cloven',
        'Comcast',
        'Common Cents Mobile',
        'Cox',
        'Disney Mobile',
        'EarthLink',
        'Embarq',
        'ESPN MVP',
        'Firefly Mobile',
        'Fuzion Mobile',
        'GIV Mobile',
        'GTC Wireless',
        'Hello US Mobile',
        'Helio',
        'iQ Cellular',
        'Itel UTel',
        'Jump Mobile',
        'Lucky Wireless',
        'Mi Gente Mobile',
        'Mingo Wireless',
        'MOSH Mobile',
        'Movida',
        'Omni Prepaid',
        'Millenicom',
        'Next G Mobile',
        'Phonata',
        'PrepaYd Wireless',
        'PTel Mobile',
        'Pure Mobile',
        'Qwest Wireless',
        'Ring Plus, Inc',
        'Shaka Mobile',
        'Simple Freedom',
        'Solavei',
        'Spot Mobile',
        'SWT Mobile',
        'TalkForGood',
        'Trumpet Mobile',
        'TúYo Mobile',
        'Univision Mobile',
        'UppWireless',
        'Voce',
        'Votel Mobile',
        'Voyager Mobile',
        'WOW Mobile PCS',
        'XCellular USA',
        'ZACT',
        'Zapp',
        'ZUMA Prepaid',
        'Armed Forces Wireless',
        'BOOM Mobile',
        'BroadBLUE',
        'DataJack',
        'EcoMobile',
        'FreedomPop',
        'Hayai Broadband',
        'H2O Wireless',
        'H2O Wireless Bolt',
        'Internet on the Go',
        'Karma',
        'Madstar Mobile',
        'MetroPCS',
        'NetZero',
        'Red Pocket Mobile',
        'Simple Mobile',
        'Selectel',
        'Ting',
        'TruConnect',
        'Virgin Mobile USA',
        'Ultra Mobile'
    ],
    'phoneBrands': [
        'Acer',
        'Alcatel',
        'Allview',
        'Amazon',
        'Amoi',
        'Apple',
        'Archos',
        'Asus',
        'At&t',
        'Benefon',
        'Benq',
        'Benq-Siemens',
        'Bird',
        'Blackberry',
        'Blu',
        'Bosch',
        'Bq',
        'Casio',
        'Cat',
        'Celkon',
        'Chea',
        'Coolpad',
        'Dell',
        'Emporia',
        'Energizer',
        'Ericsson',
        'Eten',
        'Fujitsu Siemens',
        'Garmin-Asus',
        'Gigabyte',
        'Gionee',
        'Google',
        'Haier',
        'Hp',
        'Htc',
        'Huawei',
        'I-Mate',
        'I-Mobile',
        'Icemobile',
        'Innostream',
        'Inq',
        'Intex',
        'Jolla',
        'Karbonn',
        'Kyocera',
        'Lava',
        'Leeco',
        'Lenovo',
        'Lg',
        'Maxon',
        'Maxwest',
        'Meizu',
        'Micromax',
        'Microsoft',
        'Mitac',
        'Mitsubishi',
        'Modu',
        'Motorola',
        'Mwg',
        'Nec',
        'Neonode',
        'Niu',
        'Nokia',
        'Nvidia',
        'O2',
        'Oneplus',
        'Oppo',
        'Orange',
        'Palm',
        'Panasonic',
        'Pantech',
        'Parla',
        'Philips',
        'Plum',
        'Posh',
        'Prestigio',
        'Qmobile',
        'Qtek',
        'Sagem',
        'Samsung',
        'Sendo',
        'Sewon',
        'Sharp',
        'Siemens',
        'Sonim',
        'Sony',
        'Sony Ericsson',
        'Spice',
        'T-Mobile',
        'Tel.Me.',
        'Telit',
        'Thuraya',
        'Toshiba',
        'Unnecto',
        'Vertu',
        'Verykool',
        'Vivo',
        'Vk Mobile',
        'Vodafone',
        'Wiko',
        'Wnd',
        'Xcute',
        'Xiaomi',
        'Xolo',
        'Yezz',
        'Yota',
        'Yu',
        'Zte'
    ],
    'phoneColors': [
        'white',
        'black',
        'graphite',
        'gold',
        'titanium',
        'red',
        'lime',
        'green',
        'opal',
        'cyan'
    ]
}